# Generated by Django 2.1 on 2019-01-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
